name: landscapes
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pysindy
  - pytorch
  - pytorch-lightning
  - typing_extensions
  - pyarrow
  - fastparquet
  - dill
  - pandas
  - opencv
  - plotly
  - scikit-learn
